# Generated by Django 3.1.3 on 2020-12-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201201_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='full_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
