# Generated by Django 3.1.3 on 2020-12-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201201_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id_number',
        ),
    ]
