# Generated by Django 3.1.3 on 2020-12-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_student_student_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedbook',
            name='delivered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
