# Generated by Django 3.1.3 on 2020-12-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201204_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedbook',
            name='delivered_date',
            field=models.DateTimeField(),
        ),
    ]
