# Generated by Django 3.1.3 on 2020-12-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201204_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedbook',
            name='delivered_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
