# Generated by Django 3.1.3 on 2020-12-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201204_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedbook',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedbook',
            name='purchased_date',
            field=models.DateField(auto_now=True),
        ),
    ]
