# Generated by Django 3.1.3 on 2020-12-07 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201204_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedbook',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 15, 30, 35, 998243)),
        ),
    ]
